alter view public.stores set (security_invoker = true);
alter view public.layouts set (security_invoker = true);
alter view public.floors set (security_invoker = true);
alter view public.zones set (security_invoker = true);
alter view public.aisles set (security_invoker = true);
alter view public.shelves set (security_invoker = true);
alter view public.shelf_levels set (security_invoker = true);
alter view public.shelf_slots set (security_invoker = true);
alter view public.items set (security_invoker = true);
alter view public.admin_users set (security_invoker = true);
alter view public.item_locations set (security_invoker = true);
alter view public.products set (security_invoker = true);
alter view public.inventory_balances set (security_invoker = true);

revoke all on public.stores from authenticated;
revoke all on public.layouts from authenticated;
revoke all on public.floors from authenticated;
revoke all on public.zones from authenticated;
revoke all on public.aisles from authenticated;
revoke all on public.shelves from authenticated;
revoke all on public.shelf_levels from authenticated;
revoke all on public.shelf_slots from authenticated;
revoke all on public.items from authenticated;
revoke all on public.admin_users from authenticated;
revoke all on public.item_locations from authenticated;
revoke all on public.products from authenticated;
revoke all on public.inventory_balances from authenticated;

grant select, insert, update, delete on public.stores to service_role;
grant select, insert, update, delete on public.layouts to service_role;
grant select, insert, update, delete on public.floors to service_role;
grant select, insert, update, delete on public.zones to service_role;
grant select, insert, update, delete on public.aisles to service_role;
grant select, insert, update, delete on public.shelves to service_role;
grant select, insert, update, delete on public.shelf_levels to service_role;
grant select, insert, update, delete on public.shelf_slots to service_role;
grant select, insert, update, delete on public.items to service_role;
grant select, insert, update, delete on public.admin_users to service_role;
grant select, insert, update, delete on public.item_locations to service_role;
grant select on public.products to service_role;
grant select on public.inventory_balances to service_role;
