-- Versioned retail price lists.
--
-- A price-list upload is a dated snapshot, not a destructive replacement.  The
-- existing `catalog.pricelist_import_staging` table remains the compatibility
-- surface for the public catalogue and is refreshed only when a version is
-- activated.  Historical snapshots and their prices live in the two tables
-- below, so a part omitted from a new list is retained and can be reported as
-- "not listed" rather than silently archived.

create schema if not exists catalog;

do $$
begin
  if to_regclass('catalog.products') is not null then
    execute 'alter table catalog.products add column if not exists source_category text';
  end if;
end;
$$;

create table if not exists catalog.pricelist_versions (
  id uuid primary key default gen_random_uuid(),
  price_type text not null default 'retail'
    check (price_type in ('retail', 'cost', 'wholesale', 'promo')),
  version_year integer not null check (version_year between 2000 and 2200),
  effective_from date not null,
  effective_to date,
  status text not null default 'draft'
    check (status in ('draft', 'published', 'archived')),
  is_active boolean not null default false,
  source_filename text,
  source_checksum text,
  notes text,
  row_count integer not null default 0 check (row_count >= 0),
  created_by uuid references auth.users(id) on delete set null,
  activated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  activated_at timestamptz,
  unique (price_type, version_year, effective_from)
);

create unique index if not exists pricelist_versions_one_active_idx
  on catalog.pricelist_versions (price_type)
  where is_active;

create index if not exists pricelist_versions_year_idx
  on catalog.pricelist_versions (price_type, version_year desc, effective_from desc);

create table if not exists catalog.pricelist_version_items (
  id uuid primary key default gen_random_uuid(),
  pricelist_version_id uuid not null references catalog.pricelist_versions(id) on delete cascade,
  product_id uuid references catalog.products(id) on delete set null,
  source_sheet text,
  source_line_number integer not null check (source_line_number >= 1),
  sku text not null,
  name text not null,
  model_name text,
  uom text not null default 'PC',
  pcc text,
  price numeric(12,2) not null check (price >= 0),
  status text,
  category text,
  source_category text,
  classification_version text,
  classification_confidence text,
  classification_strategy text,
  classification_rule_key text,
  classification_tokens jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (pricelist_version_id, sku)
);

create index if not exists pricelist_version_items_sku_idx
  on catalog.pricelist_version_items (sku);

create index if not exists pricelist_version_items_product_idx
  on catalog.pricelist_version_items (product_id);

-- The current staging table predates versioning and is not present in every
-- isolated bootstrap.  Create the compatible shape when it is missing and
-- add only nullable metadata columns when it already exists.
create table if not exists catalog.pricelist_import_staging (
  id bigint generated by default as identity primary key,
  source_sheet text,
  source_line_number integer not null,
  sku text not null,
  name text not null,
  model_name text,
  uom text not null default 'PC',
  pcc text,
  price numeric(12,2) not null check (price >= 0),
  status text,
  category text,
  source_category text,
  classification_version text,
  classification_confidence text,
  classification_strategy text,
  classification_rule_key text,
  classification_tokens jsonb not null default '[]'::jsonb,
  imported_at timestamptz not null default timezone('utc', now())
);

alter table catalog.pricelist_import_staging
  add column if not exists pricelist_version_id uuid;
alter table catalog.pricelist_import_staging
  add column if not exists version_year integer;

create index if not exists pricelist_staging_version_idx
  on catalog.pricelist_import_staging (pricelist_version_id, source_line_number);

alter table catalog.pricelist_versions enable row level security;
alter table catalog.pricelist_version_items enable row level security;

drop policy if exists service_role_pricelist_versions_all on catalog.pricelist_versions;
create policy service_role_pricelist_versions_all
  on catalog.pricelist_versions
  for all to service_role
  using (true)
  with check (true);

drop policy if exists service_role_pricelist_version_items_all on catalog.pricelist_version_items;
create policy service_role_pricelist_version_items_all
  on catalog.pricelist_version_items
  for all to service_role
  using (true)
  with check (true);

revoke all on catalog.pricelist_versions from public, anon, authenticated;
revoke all on catalog.pricelist_version_items from public, anon, authenticated;
grant select, insert, update, delete on catalog.pricelist_versions to service_role;
grant select, insert, update, delete on catalog.pricelist_version_items to service_role;

create or replace function public.import_retail_pricelist_version(
  p_items jsonb,
  p_version_year integer,
  p_effective_from date,
  p_source_filename text default null,
  p_activate boolean default true,
  p_actor_id uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, catalog
as $function$
declare
  v_now timestamptz := timezone('utc', now());
  v_version_id uuid;
  v_previous_version_id uuid;
  v_received_count integer := 0;
  v_unique_count integer := 0;
  v_new_products_count integer := 0;
  v_stock_rows_created integer := 0;
  v_changed_count integer := 0;
  v_unchanged_count integer := 0;
  v_added_count integer := 0;
  v_removed_count integer := 0;
  v_price_increase_count integer := 0;
  v_price_decrease_count integer := 0;
begin
  if jsonb_typeof(p_items) <> 'array' then
    raise exception using errcode = '22023', message = 'Price list items must be a JSON array.';
  end if;

  if p_version_year is null or p_version_year < 2000 or p_version_year > 2200 then
    raise exception using errcode = '22023', message = 'Price list year must be between 2000 and 2200.';
  end if;

  if p_effective_from is null then
    raise exception using errcode = '22023', message = 'Price list effective date is required.';
  end if;

  -- Serialize activation and current-price replacement.  This prevents two
  -- simultaneous uploads from each observing the other as the active list.
  perform pg_catalog.pg_advisory_xact_lock(73841590214631::bigint);

  if not p_activate and exists (
    select 1
    from catalog.pricelist_versions
    where price_type = 'retail'
      and version_year = p_version_year
      and effective_from = p_effective_from
      and is_active = true
  ) then
    raise exception using
      errcode = '22023',
      message = 'The active price list cannot be replaced as a draft. Apply it immediately or choose a new effective date.';
  end if;

  create temporary table _retail_pricelist_version_raw (
    source_line_number integer not null,
    sku text not null,
    name text,
    model_name text,
    uom text,
    pcc text,
    price numeric(12,2) not null,
    status text,
    category text,
    source_category text,
    classification_version text,
    classification_confidence text,
    classification_strategy text,
    classification_rule_key text,
    classification_tokens jsonb not null default '[]'::jsonb
  ) on commit drop;

  insert into _retail_pricelist_version_raw (
    source_line_number, sku, name, model_name, uom, pcc, price, status,
    category, source_category, classification_version,
    classification_confidence, classification_strategy,
    classification_rule_key, classification_tokens
  )
  select
    entry.ordinality::integer,
    pg_catalog.upper(pg_catalog.btrim(entry.value ->> 'sku')),
    nullif(pg_catalog.btrim(entry.value ->> 'name'), ''),
    nullif(pg_catalog.btrim(coalesce(entry.value ->> 'model', entry.value ->> 'application')), ''),
    coalesce(nullif(pg_catalog.btrim(entry.value ->> 'uom'), ''), 'PC'),
    nullif(pg_catalog.btrim(entry.value ->> 'pcc'), ''),
    round((entry.value ->> 'price')::numeric, 2),
    nullif(pg_catalog.btrim(entry.value ->> 'status'), ''),
    nullif(pg_catalog.btrim(entry.value ->> 'category'), ''),
    nullif(pg_catalog.btrim(coalesce(entry.value ->> 'sourceCategory', entry.value ->> 'category')), ''),
    nullif(pg_catalog.btrim(entry.value ->> 'classificationVersion'), ''),
    nullif(pg_catalog.btrim(entry.value ->> 'classificationConfidence'), ''),
    nullif(pg_catalog.btrim(entry.value ->> 'classificationStrategy'), ''),
    nullif(pg_catalog.btrim(entry.value ->> 'classificationRuleKey'), ''),
    case when jsonb_typeof(entry.value -> 'classificationTokens') = 'array'
      then entry.value -> 'classificationTokens' else '[]'::jsonb end
  from pg_catalog.jsonb_array_elements(p_items) with ordinality as entry(value, ordinality)
  where pg_catalog.btrim(entry.value ->> 'sku') <> '';

  select count(*) into v_received_count from _retail_pricelist_version_raw;
  if v_received_count = 0 then
    raise exception using errcode = '22023', message = 'Provide at least one valid part number and price.';
  end if;

  create temporary table _retail_pricelist_version_items on commit drop as
  select distinct on (sku)
    source_line_number, sku, coalesce(name, sku) as name, model_name,
    coalesce(uom, 'PC') as uom, pcc, price, status, category, source_category,
    classification_version, classification_confidence, classification_strategy,
    classification_rule_key, classification_tokens
  from _retail_pricelist_version_raw
  order by sku, source_line_number;

  select count(*) into v_unique_count from _retail_pricelist_version_items;

  create temporary table _retail_pricelist_previous_prices (
    sku text primary key,
    name text,
    price numeric(12,2) not null
  ) on commit drop;

  select id into v_previous_version_id
  from catalog.pricelist_versions
  where price_type = 'retail' and is_active = true
  order by activated_at desc nulls last, updated_at desc
  limit 1;

  if v_previous_version_id is not null then
    insert into _retail_pricelist_previous_prices (sku, name, price)
    select sku, name, price
    from catalog.pricelist_version_items
    where pricelist_version_id = v_previous_version_id;
  end if;

  -- A pre-versioned installation may have current product_prices but no active
  -- snapshot.  Use those rows as the comparison baseline for the first import.
  if to_regclass('catalog.products') is not null
    and to_regclass('catalog.product_prices') is not null then
    insert into _retail_pricelist_previous_prices (sku, name, price)
    select product.sku, product.name, current_price.amount
    from catalog.products product
    join catalog.product_prices current_price
      on current_price.product_id = product.id
     and current_price.price_type = 'retail'
     and current_price.is_current = true
    where not exists (
      select 1 from _retail_pricelist_previous_prices previous where previous.sku = product.sku
    );
  end if;

  insert into catalog.pricelist_versions (
    price_type, version_year, effective_from, status, is_active,
    source_filename, row_count, created_by, updated_at
  )
  values (
    'retail', p_version_year, p_effective_from,
    case when p_activate then 'published' else 'draft' end,
    false, nullif(pg_catalog.btrim(p_source_filename), ''), v_unique_count,
    p_actor_id, v_now
  )
  on conflict (price_type, version_year, effective_from) do update set
    status = case when p_activate then 'published' else 'draft' end,
    is_active = false,
    source_filename = coalesce(excluded.source_filename, catalog.pricelist_versions.source_filename),
    row_count = excluded.row_count,
    updated_at = excluded.updated_at
  returning id into v_version_id;

  delete from catalog.pricelist_version_items
  where pricelist_version_id = v_version_id;

  if to_regclass('catalog.products') is null then
    raise exception using errcode = '42P01', message = 'catalog.products is required before importing a price list.';
  end if;

  select count(*) into v_new_products_count
  from _retail_pricelist_version_items item
  left join catalog.products product on product.sku = item.sku
  where product.id is null;

  insert into catalog.products (
    sku, name, model_name, category, brand, uom, status, is_active,
    source_category, metadata, business_date, updated_at
  )
  select
    item.sku,
    item.name,
    item.model_name,
    coalesce(item.category, 'General Parts & Accessories'),
    'Mitsubishi',
    item.uom,
    'out_of_stock',
    true,
    item.source_category,
    pg_catalog.jsonb_build_object('priceListVersionYear', p_version_year),
    p_effective_from,
    v_now
  from _retail_pricelist_version_items item
  on conflict (sku) do update set
    name = case
      when catalog.products.name is null or catalog.products.name = catalog.products.sku
        then excluded.name else catalog.products.name end,
    model_name = coalesce(excluded.model_name, catalog.products.model_name),
    category = coalesce(excluded.category, catalog.products.category),
    source_category = coalesce(excluded.source_category, catalog.products.source_category),
    is_active = true,
    status = case when catalog.products.status = 'discontinued' then 'out_of_stock' else catalog.products.status end,
    metadata = coalesce(catalog.products.metadata, '{}'::jsonb)
      || pg_catalog.jsonb_build_object('priceListVersionYear', p_version_year),
      updated_at = excluded.updated_at;

  insert into catalog.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date, business_date)
  select product.id, 0, 0, 0, 0, '{}'::jsonb, p_effective_from, p_effective_from
  from catalog.products product
  join _retail_pricelist_version_items item on item.sku = product.sku
  where not exists (
    select 1 from catalog.inventory_balances balance where balance.product_id = product.id
  )
  on conflict (product_id) do nothing;
  get diagnostics v_stock_rows_created = row_count;

  insert into catalog.pricelist_version_items (
    pricelist_version_id, product_id, source_sheet, source_line_number,
    sku, name, model_name, uom, pcc, price, status, category, source_category,
    classification_version, classification_confidence, classification_strategy,
    classification_rule_key, classification_tokens, updated_at
  )
  select
    v_version_id, product.id, null, item.source_line_number, item.sku, item.name,
    item.model_name, item.uom, item.pcc, item.price, item.status, item.category,
    item.source_category, item.classification_version,
    item.classification_confidence, item.classification_strategy,
    item.classification_rule_key, item.classification_tokens, v_now
  from _retail_pricelist_version_items item
  join catalog.products product on product.sku = item.sku;

  create temporary table _retail_pricelist_changes on commit drop as
  select
    coalesce(current_item.sku, previous.sku) as sku,
    coalesce(current_item.name, previous.name) as name,
    previous.price as previous_price,
    current_item.price as new_price,
    case
      when previous.sku is null then 'new_part'
      when current_item.sku is null then 'removed_from_list'
      when previous.price <> current_item.price then 'new_price'
      else 'unchanged'
    end as change_status,
    case
      when previous.price is null or current_item.price is null then null
      else round(current_item.price - previous.price, 2)
    end as difference
  from (
    select sku, name, price
    from catalog.pricelist_version_items
    where pricelist_version_id = v_version_id
  ) current_item
  full join _retail_pricelist_previous_prices previous on previous.sku = current_item.sku;

  select count(*) filter (where change_status = 'new_part'),
         count(*) filter (where change_status = 'removed_from_list'),
         count(*) filter (where change_status = 'new_price'),
         count(*) filter (where change_status = 'unchanged'),
         count(*) filter (where change_status = 'new_price' and difference > 0),
         count(*) filter (where change_status = 'new_price' and difference < 0)
  into v_added_count, v_removed_count, v_changed_count, v_unchanged_count,
       v_price_increase_count, v_price_decrease_count
  from _retail_pricelist_changes;

  if p_activate then
    update catalog.pricelist_versions
    set is_active = false, updated_at = v_now
    where price_type = 'retail' and id <> v_version_id;

    update catalog.pricelist_versions
    set status = 'published', is_active = true, activated_by = p_actor_id,
        activated_at = v_now, updated_at = v_now
    where id = v_version_id;

    if to_regclass('catalog.product_prices') is not null then
      update catalog.product_prices
      set is_current = false, effective_to = p_effective_from, updated_at = v_now
      where price_type = 'retail' and is_current = true;

      insert into catalog.product_prices (
        product_id, price_type, amount, currency, effective_from,
        effective_to, is_current, business_date, updated_at
      )
      select product.id, 'retail', item.price, 'PHP', p_effective_from,
             null, true, p_effective_from, v_now
      from catalog.pricelist_version_items item
      join catalog.products product on product.id = item.product_id
      where item.pricelist_version_id = v_version_id;
    end if;

    -- Keep the legacy staging surface aligned with the active snapshot.  The
    -- version tables are the durable history; this table is only a compatibility
    -- projection for existing catalogue and quote code.
    delete from catalog.pricelist_import_staging;
    insert into catalog.pricelist_import_staging (
      source_sheet, source_line_number, sku, name, model_name, uom, pcc, price,
      status, category, source_category, classification_version,
      classification_confidence, classification_strategy, classification_rule_key,
      classification_tokens, imported_at, pricelist_version_id, version_year
    )
    select item.source_sheet, item.source_line_number, item.sku, item.name,
      item.model_name, item.uom, item.pcc, item.price, item.status, item.category,
      item.source_category, item.classification_version,
      item.classification_confidence, item.classification_strategy,
      item.classification_rule_key, item.classification_tokens, v_now,
      item.pricelist_version_id, p_version_year
    from catalog.pricelist_version_items item
    where item.pricelist_version_id = v_version_id;
  end if;

  return pg_catalog.jsonb_build_object(
    'versionId', v_version_id,
    'versionYear', p_version_year,
    'effectiveFrom', p_effective_from,
    'status', case when p_activate then 'published' else 'draft' end,
    'isActive', p_activate,
    'receivedCount', v_received_count,
    'uniqueCount', v_unique_count,
    'updatedCount', v_unique_count,
    'changedCount', v_changed_count + v_added_count,
    'unchangedCount', v_unchanged_count,
    'newProductsCount', v_added_count,
    'archivedProductsCount', 0,
    'removedFromListCount', v_removed_count,
    'priceIncreaseCount', v_price_increase_count,
    'priceDecreaseCount', v_price_decrease_count,
    'stockRowsCreated', v_stock_rows_created,
    'skippedCount', 0,
    'skippedItems', '[]'::jsonb,
    'priceChangesTotalCount', v_changed_count + v_added_count + v_removed_count,
    'priceChanges', coalesce((
      select pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object(
        'sku', sku,
        'name', name,
        'previousPrice', previous_price,
        'newPrice', new_price,
        'difference', difference,
        'status', change_status
      ) order by sku)
      from (select * from _retail_pricelist_changes where change_status <> 'unchanged' order by sku limit 500) preview
    ), '[]'::jsonb)
  );
end;
$function$;

create or replace function public.activate_retail_pricelist_version(p_version_id uuid, p_actor_id uuid default null)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, catalog
as $function$
declare
  v_version catalog.pricelist_versions%rowtype;
  v_now timestamptz := timezone('utc', now());
begin
  perform pg_catalog.pg_advisory_xact_lock(73841590214631::bigint);

  select * into v_version
  from catalog.pricelist_versions
  where id = p_version_id and price_type = 'retail'
  for update;

  if not found then
    raise exception using errcode = '22023', message = 'Price list version was not found.';
  end if;

  update catalog.pricelist_versions
  set is_active = false, updated_at = v_now
  where price_type = 'retail' and id <> p_version_id;

  update catalog.pricelist_versions
  set status = 'published', is_active = true, activated_by = p_actor_id,
      activated_at = v_now, updated_at = v_now
  where id = p_version_id;

  update catalog.product_prices
  set is_current = false, effective_to = v_version.effective_from, updated_at = v_now
  where price_type = 'retail' and is_current = true;

  insert into catalog.product_prices (
    product_id, price_type, amount, currency, effective_from, effective_to,
    is_current, business_date, updated_at
  )
  select item.product_id, 'retail', item.price, 'PHP', v_version.effective_from,
    null, true, v_version.effective_from, v_now
  from catalog.pricelist_version_items item
  where item.pricelist_version_id = p_version_id and item.product_id is not null;

  delete from catalog.pricelist_import_staging;
  insert into catalog.pricelist_import_staging (
    source_sheet, source_line_number, sku, name, model_name, uom, pcc, price,
    status, category, source_category, classification_version,
    classification_confidence, classification_strategy, classification_rule_key,
    classification_tokens, imported_at, pricelist_version_id, version_year
  )
  select item.source_sheet, item.source_line_number, item.sku, item.name,
    item.model_name, item.uom, item.pcc, item.price, item.status, item.category,
    item.source_category, item.classification_version,
    item.classification_confidence, item.classification_strategy,
    item.classification_rule_key, item.classification_tokens, v_now,
    item.pricelist_version_id, v_version.version_year
  from catalog.pricelist_version_items item
  where item.pricelist_version_id = p_version_id;

  return pg_catalog.jsonb_build_object(
    'versionId', p_version_id,
    'versionYear', v_version.version_year,
    'effectiveFrom', v_version.effective_from,
    'status', 'published',
    'isActive', true,
    'itemCount', v_version.row_count
  );
end;
$function$;

revoke all on function public.import_retail_pricelist_version(jsonb, integer, date, text, boolean, uuid) from public, anon, authenticated;
revoke all on function public.activate_retail_pricelist_version(uuid, uuid) from public, anon, authenticated;
grant execute on function public.import_retail_pricelist_version(jsonb, integer, date, text, boolean, uuid) to service_role;
grant execute on function public.activate_retail_pricelist_version(uuid, uuid) to service_role;
