-- Product Catalog Seed Part 2 of 4


insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MN171260', 'BOOT,CLUTCH RELEASE FORK', 'STRADA CR (2005-2013)', 'Clutch', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 115.36, true, current_date from app.products where sku = 'MN171260' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 23.00, 0, 6, 12, '{"floor":1,"section":"H","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MN171260' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2590A134', 'SPRING,M/T GEARSHIFT EQUIP', 'STRADA CR (2005-2013)', 'Suspension', 'Mitsubishi', 'PC', 'out_of_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 47.04, true, current_date from app.products where sku = '2590A134' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 49.00, 0, 13, 25, '{"floor":2,"section":"A","shelf":"5"}'::jsonb, current_date from app.products where sku = '2590A134' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2526A016', 'GEAR, MT O/PUT SHAFT 5TH SPEED', 'STRADA CR (2005-2013)', 'Transmission', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 3459.68, true, current_date from app.products where sku = '2526A016' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 2.00, 0, 1, 1, '{"floor":2,"section":"B","shelf":"1"}'::jsonb, current_date from app.products where sku = '2526A016' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('4600A138', 'RETAINER, RR BRAKE', 'STRADA CR (2005-2013)', 'Brakes', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 90.72, true, current_date from app.products where sku = '4600A138' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 39.00, 0, 10, 20, '{"floor":1,"section":"C","shelf":"2"}'::jsonb, current_date from app.products where sku = '4600A138' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8395A055', 'SOCKET,FR LAMP', 'STRADA CR (2005-2013)', 'Lighting', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 169.12, true, current_date from app.products where sku = '8395A055' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 36.00, 0, 9, 18, '{"floor":2,"section":"D","shelf":"3"}'::jsonb, current_date from app.products where sku = '8395A055' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('5725A075', 'CLIP,FR DOOR', 'STRADA CR (2005-2013)', 'Body Parts', 'Mitsubishi', 'PC', 'out_of_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 53.76, true, current_date from app.products where sku = '5725A075' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 48.00, 0, 12, 24, '{"floor":2,"section":"E","shelf":"4"}'::jsonb, current_date from app.products where sku = '5725A075' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8558A031HA', 'GARNISH,CLOCK', 'STRADA CR (2005-2013)', 'Accessories', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 38.08, true, current_date from app.products where sku = '8558A031HA' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 9.00, 0, 3, 5, '{"floor":1,"section":"F","shelf":"5"}'::jsonb, current_date from app.products where sku = '8558A031HA' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MN123604', 'HOSE,A/C EVAPORATOR DRAIN', 'STRADA CR (2005-2013)', 'Air Conditioning', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 372.96, true, current_date from app.products where sku = 'MN123604' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 39.00, 0, 10, 20, '{"floor":2,"section":"G","shelf":"1"}'::jsonb, current_date from app.products where sku = 'MN123604' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF911140', 'BOLT,CYLINDER BLOCK', 'MIRAGE G4 (2012-PRESENT)', 'Engine', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 31.36, true, current_date from app.products where sku = 'MF911140' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 44.00, 0, 11, 22, '{"floor":2,"section":"H","shelf":"2"}'::jsonb, current_date from app.products where sku = 'MF911140' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1748A246', 'CLIP,FUEL LINE', 'MIRAGE G4 (2012-PRESENT)', 'General Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 20.16, true, current_date from app.products where sku = '1748A246' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 30.00, 0, 8, 15, '{"floor":1,"section":"A","shelf":"3"}'::jsonb, current_date from app.products where sku = '1748A246' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('5736A401', 'W/STRIP,RR DOOR BELT,INR L', 'MIRAGE G4 (2012-PRESENT)', 'Belts & Pulleys', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 928.48, true, current_date from app.products where sku = '5736A401' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 10.00, 0, 3, 5, '{"floor":2,"section":"B","shelf":"4"}'::jsonb, current_date from app.products where sku = '5736A401' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1300A108', 'O-RING,WATER PUMP', 'MIRAGE G4 (2012-PRESENT)', 'Cooling', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 147.84, true, current_date from app.products where sku = '1300A108' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 20.00, 0, 5, 10, '{"floor":2,"section":"C","shelf":"5"}'::jsonb, current_date from app.products where sku = '1300A108' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('5740A196', 'PAD,RR DOOR INR PANEL', 'MIRAGE G4 (2012-PRESENT)', 'Body Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 35.84, true, current_date from app.products where sku = '5740A196' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 49.00, 0, 13, 25, '{"floor":1,"section":"D","shelf":"1"}'::jsonb, current_date from app.products where sku = '5740A196' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8558B181', 'BRACKET,INLET MANIFOLD', 'MIRAGE G4 (2012-PRESENT)', 'Steering', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 140.00, true, current_date from app.products where sku = '8558B181' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 29.00, 0, 8, 15, '{"floor":2,"section":"E","shelf":"2"}'::jsonb, current_date from app.products where sku = '8558B181' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('7810A044', 'BOLT,A/C', 'MIRAGE G4 (2012-PRESENT)', 'Air Conditioning', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 40.32, true, current_date from app.products where sku = '7810A044' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 5.00, 0, 2, 3, '{"floor":2,"section":"F","shelf":"3"}'::jsonb, current_date from app.products where sku = '7810A044' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1577A415', 'BOLT,EXHAUST PIPE', 'MIRAGE G4 (2012-PRESENT)', 'Exhaust', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 87.36, true, current_date from app.products where sku = '1577A415' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 36.00, 0, 9, 18, '{"floor":1,"section":"G","shelf":"4"}'::jsonb, current_date from app.products where sku = '1577A415' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8002B467XA', 'LID,INST PANEL FUSE BOX', 'MIRAGE G4 (2012-PRESENT)', 'Electrical', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 174.72, true, current_date from app.products where sku = '8002B467XA' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 12.00, 0, 3, 6, '{"floor":2,"section":"H","shelf":"5"}'::jsonb, current_date from app.products where sku = '8002B467XA' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('7821A126', 'BULB,HEATER CONTROL PANEL', 'MIRAGE G4 (2012-PRESENT)', 'Lighting', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 70.56, true, current_date from app.products where sku = '7821A126' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 4.00, 0, 1, 2, '{"floor":2,"section":"A","shelf":"1"}'::jsonb, current_date from app.products where sku = '7821A126' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8606A002', 'SWITCH,CLUTCH', 'MIRAGE G4 (2012-PRESENT)', 'Clutch', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 580.16, true, current_date from app.products where sku = '8606A002' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 23.00, 0, 6, 12, '{"floor":1,"section":"B","shelf":"2"}'::jsonb, current_date from app.products where sku = '8606A002' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2528A439', 'GEAR,M/T OUTPUT SHAFT 3RD', 'MIRAGE G4 (2012-PRESENT)', 'Transmission', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 2521.12, true, current_date from app.products where sku = '2528A439' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 39.00, 0, 10, 20, '{"floor":2,"section":"C","shelf":"3"}'::jsonb, current_date from app.products where sku = '2528A439' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2585A032', 'SPRING,M/T GEARSHIFT EQUIP', 'MIRAGE G4 (2012-PRESENT)', 'Suspension', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 49.28, true, current_date from app.products where sku = '2585A032' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 31.00, 0, 8, 16, '{"floor":2,"section":"D","shelf":"4"}'::jsonb, current_date from app.products where sku = '2585A032' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('288B4W040P', 'BLADE,WINDSHIELD WIPER,LH', 'MIRAGE G4 (2012-PRESENT)', 'Accessories', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 224.00, true, current_date from app.products where sku = '288B4W040P' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 49.00, 0, 13, 25, '{"floor":1,"section":"E","shelf":"5"}'::jsonb, current_date from app.products where sku = '288B4W040P' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2921A007', 'OIL FILTER,A/T CASE', 'MIRAGE G4 (2012-PRESENT)', 'Filters', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 390.88, true, current_date from app.products where sku = '2921A007' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 43.00, 0, 11, 22, '{"floor":2,"section":"F","shelf":"1"}'::jsonb, current_date from app.products where sku = '2921A007' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('CP4650B874', 'CLIP,BRAKE FLUID LINE', 'MIRAGE G4 (2012-PRESENT)', 'Brakes', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 0.01, true, current_date from app.products where sku = 'CP4650B874' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 7.00, 0, 2, 4, '{"floor":2,"section":"G","shelf":"2"}'::jsonb, current_date from app.products where sku = 'CP4650B874' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF201523', 'SCREW,SPARK PLUG CABLE', 'MIRAGE G4 (2012-PRESENT)', 'Ignition', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 154.56, true, current_date from app.products where sku = 'MF201523' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 44.00, 0, 11, 22, '{"floor":1,"section":"H","shelf":"3"}'::jsonb, current_date from app.products where sku = 'MF201523' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF244824', 'BOLT,CRANKSHAFT', 'MIRAGE HB (2012-PRESENT)', 'Engine', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 51.52, true, current_date from app.products where sku = 'MF244824' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 35.00, 0, 9, 18, '{"floor":2,"section":"A","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MF244824' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1010A412', 'RETAINER,VALVE SPRING', 'MIRAGE HB (2012-PRESENT)', 'Suspension', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 95.20, true, current_date from app.products where sku = '1010A412' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 7.00, 0, 2, 4, '{"floor":2,"section":"B","shelf":"5"}'::jsonb, current_date from app.products where sku = '1010A412' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1577A390', 'HANGER,EXHAUST MUFFLER', 'MIRAGE HB (2012-PRESENT)', 'Exhaust', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 271.04, true, current_date from app.products where sku = '1577A390' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 38.00, 0, 10, 19, '{"floor":1,"section":"C","shelf":"1"}'::jsonb, current_date from app.products where sku = '1577A390' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF911060', 'BOLT,ENG CONTROL UNIT', 'MIRAGE HB (2012-PRESENT)', 'General Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 38.08, true, current_date from app.products where sku = 'MF911060' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 49.00, 0, 13, 25, '{"floor":2,"section":"D","shelf":"2"}'::jsonb, current_date from app.products where sku = 'MF911060' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1340A128', 'BELT,ALTERNATOR & OTHERS', 'MIRAGE HB (2012-PRESENT)', 'Belts & Pulleys', 'Mitsubishi', 'PC', 'out_of_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 766.08, true, current_date from app.products where sku = '1340A128' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 17.00, 0, 5, 9, '{"floor":2,"section":"E","shelf":"3"}'::jsonb, current_date from app.products where sku = '1340A128' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1120A069', 'RING GEAR,FLYWHEEL', 'MIRAGE HB (2012-PRESENT)', 'Transmission', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 6147.68, true, current_date from app.products where sku = '1120A069' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 24.00, 0, 6, 12, '{"floor":1,"section":"F","shelf":"4"}'::jsonb, current_date from app.products where sku = '1120A069' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('PA1351A054', 'INSULATOR,RADIATOR SUPPORT,UPR', 'MIRAGE HB (2012-PRESENT)', 'Cooling', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 124.32, true, current_date from app.products where sku = 'PA1351A054' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 19.00, 0, 5, 10, '{"floor":2,"section":"G","shelf":"5"}'::jsonb, current_date from app.products where sku = 'PA1351A054' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('5729A053', 'PAD,FR DOOR INR PANEL', 'MIRAGE HB (2012-PRESENT)', 'Body Parts', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 38.08, true, current_date from app.products where sku = '5729A053' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 39.00, 0, 10, 20, '{"floor":2,"section":"H","shelf":"1"}'::jsonb, current_date from app.products where sku = '5729A053' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('7815A987', 'CLIP, A/C PIPING', 'MIRAGE HB (2012-PRESENT)', 'Air Conditioning', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 86.24, true, current_date from app.products where sku = '7815A987' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 27.00, 0, 7, 14, '{"floor":1,"section":"A","shelf":"2"}'::jsonb, current_date from app.products where sku = '7815A987' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('DP010713', 'MOTOLITE SERVICE BATTERY [NS40', 'MIRAGE HB (2012-PRESENT)', 'Electrical', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 0.01, true, current_date from app.products where sku = 'DP010713' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 50.00, 0, 13, 25, '{"floor":2,"section":"B","shelf":"3"}'::jsonb, current_date from app.products where sku = 'DP010713' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1822A152', 'SPARK PLUG', 'MIRAGE HB (2012-PRESENT)', 'Ignition', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 1321.60, true, current_date from app.products where sku = '1822A152' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 26.00, 0, 7, 13, '{"floor":2,"section":"C","shelf":"4"}'::jsonb, current_date from app.products where sku = '1822A152' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF913110', 'BOLT,FREEWHEEL CLUTCH CONT', 'MIRAGE HB (2012-PRESENT)', 'Clutch', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 41.44, true, current_date from app.products where sku = 'MF913110' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 13.00, 0, 4, 7, '{"floor":1,"section":"D","shelf":"5"}'::jsonb, current_date from app.products where sku = 'MF913110' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2824A021', 'OIL FILTER,A/T VALVE BODY', 'MIRAGE HB (2012-PRESENT)', 'Filters', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 776.16, true, current_date from app.products where sku = '2824A021' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 31.00, 0, 8, 16, '{"floor":2,"section":"E","shelf":"1"}'::jsonb, current_date from app.products where sku = '2824A021' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8558A932', 'BRACKET,A/T HARNESS', 'MIRAGE HB (2012-PRESENT)', 'Steering', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 131.04, true, current_date from app.products where sku = '8558A932' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 48.00, 0, 12, 24, '{"floor":2,"section":"F","shelf":"2"}'::jsonb, current_date from app.products where sku = '8558A932' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MB870930', 'NUT,RR BRAKE', 'MIRAGE HB (2012-PRESENT)', 'Brakes', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 82.88, true, current_date from app.products where sku = 'MB870930' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 28.00, 0, 7, 14, '{"floor":1,"section":"G","shelf":"3"}'::jsonb, current_date from app.products where sku = 'MB870930' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8341A171', 'LENS,LICENSE PLATE LAMP', 'MIRAGE HB (2012-PRESENT)', 'Lighting', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 79.52, true, current_date from app.products where sku = '8341A171' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 17.00, 0, 5, 9, '{"floor":2,"section":"H","shelf":"4"}'::jsonb, current_date from app.products where sku = '8341A171' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8253A103', 'GROMMET,RR WINDOW WIPER', 'MIRAGE HB (2012-PRESENT)', 'Accessories', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 123.20, true, current_date from app.products where sku = '8253A103' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 39.00, 0, 10, 20, '{"floor":2,"section":"A","shelf":"5"}'::jsonb, current_date from app.products where sku = '8253A103' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MN187145', 'GASKET,F/INJ NOZZLE HOLDER', 'PAJERO (2006-PRESENT)', 'Engine', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 44.80, true, current_date from app.products where sku = 'MN187145' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 15.00, 0, 4, 8, '{"floor":1,"section":"B","shelf":"1"}'::jsonb, current_date from app.products where sku = 'MN187145' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('CP7030A829', 'INFLATOR KIT, AIR BAG', 'PAJERO (2006-PRESENT)', 'General Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 0.01, true, current_date from app.products where sku = 'CP7030A829' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 11.00, 0, 3, 6, '{"floor":2,"section":"C","shelf":"2"}'::jsonb, current_date from app.products where sku = 'CP7030A829' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1010A330', 'SPRING,EXHAUST VALVE', 'PAJERO (2006-PRESENT)', 'Suspension', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 184.80, true, current_date from app.products where sku = '1010A330' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 39.00, 0, 10, 20, '{"floor":2,"section":"D","shelf":"3"}'::jsonb, current_date from app.products where sku = '1010A330' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MR529713', 'GASKET,CATALYTIC CONVERTER', 'PAJERO (2006-PRESENT)', 'Exhaust', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 285.60, true, current_date from app.products where sku = 'MR529713' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 32.00, 0, 8, 16, '{"floor":1,"section":"E","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MR529713' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1125A218', 'GEAR,BAL SHAFT DRVN,L', 'PAJERO (2006-PRESENT)', 'Transmission', 'Mitsubishi', 'PC', 'out_of_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 7912.80, true, current_date from app.products where sku = '1125A218' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 30.00, 0, 8, 15, '{"floor":2,"section":"F","shelf":"5"}'::jsonb, current_date from app.products where sku = '1125A218' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1141A045', 'TENSIONER,TIMING CHAIN', 'PAJERO (2006-PRESENT)', 'Belts & Pulleys', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 2825.76, true, current_date from app.products where sku = '1141A045' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 30.00, 0, 8, 15, '{"floor":2,"section":"G","shelf":"1"}'::jsonb, current_date from app.products where sku = '1141A045' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1770A076', 'SENSOR,FUEL FILTER', 'PAJERO (2006-PRESENT)', 'Filters', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 3240.16, true, current_date from app.products where sku = '1770A076' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 48.00, 0, 12, 24, '{"floor":1,"section":"H","shelf":"2"}'::jsonb, current_date from app.products where sku = '1770A076' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1375A212', 'HOSE,RADIATOR COND TANK', 'PAJERO (2006-PRESENT)', 'Cooling', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 131.04, true, current_date from app.products where sku = '1375A212' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 36.00, 0, 9, 18, '{"floor":2,"section":"A","shelf":"3"}'::jsonb, current_date from app.products where sku = '1375A212' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('7801A412', 'THERMISTOR,A/C', 'PAJERO (2006-PRESENT)', 'Air Conditioning', 'Mitsubishi', 'PC', 'out_of_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 639.52, true, current_date from app.products where sku = '7801A412' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 19.00, 0, 5, 10, '{"floor":2,"section":"B","shelf":"4"}'::jsonb, current_date from app.products where sku = '7801A412' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8652A011', 'BRKT,RR SUSP HEIGHT SENSOR', 'PAJERO (2006-PRESENT)', 'Electrical', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 255.36, true, current_date from app.products where sku = '8652A011' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 22.00, 0, 6, 11, '{"floor":1,"section":"C","shelf":"5"}'::jsonb, current_date from app.products where sku = '8652A011' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MS241187', 'BOLT,HEADLAMP', 'PAJERO (2006-PRESENT)', 'Lighting', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 109.76, true, current_date from app.products where sku = 'MS241187' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 28.00, 0, 7, 14, '{"floor":2,"section":"D","shelf":"1"}'::jsonb, current_date from app.products where sku = 'MS241187' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2721A048', 'SNAP RING,A/T CLUTCH', 'PAJERO (2006-PRESENT)', 'Clutch', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 106.40, true, current_date from app.products where sku = '2721A048' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 43.00, 0, 11, 22, '{"floor":2,"section":"E","shelf":"2"}'::jsonb, current_date from app.products where sku = '2721A048' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('4605A466', 'CLIP,FR BRAKE', 'PAJERO (2006-PRESENT)', 'Brakes', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 123.20, true, current_date from app.products where sku = '4605A466' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 41.00, 0, 11, 21, '{"floor":1,"section":"F","shelf":"3"}'::jsonb, current_date from app.products where sku = '4605A466' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('5370B329', 'BRACKET,FR MUD GUARD,LH', 'PAJERO (2006-PRESENT)', 'Steering', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 218.40, true, current_date from app.products where sku = '5370B329' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 49.00, 0, 13, 25, '{"floor":2,"section":"G","shelf":"4"}'::jsonb, current_date from app.products where sku = '5370B329' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MS450973', 'SCREW,RR BUMPER', 'PAJERO (2006-PRESENT)', 'Body Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 109.76, true, current_date from app.products where sku = 'MS450973' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 49.00, 0, 13, 25, '{"floor":2,"section":"H","shelf":"5"}'::jsonb, current_date from app.products where sku = 'MS450973' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('7405A505', 'GARNISH,FR DECK SIDE,LH', 'PAJERO (2006-PRESENT)', 'Accessories', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 274.40, true, current_date from app.products where sku = '7405A505' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 33.00, 0, 9, 17, '{"floor":1,"section":"A","shelf":"1"}'::jsonb, current_date from app.products where sku = '7405A505' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('11561A000P', 'BOLT,CYLINDER BLOCK', 'TRITON (2023-PRESENT)', 'Engine', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 26.88, true, current_date from app.products where sku = '11561A000P' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 49.00, 0, 13, 25, '{"floor":2,"section":"B","shelf":"2"}'::jsonb, current_date from app.products where sku = '11561A000P' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('6979A542', 'NUT,RR SEAT', 'TRITON (2023-PRESENT)', 'General Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 10.08, true, current_date from app.products where sku = '6979A542' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 50.00, 0, 13, 25, '{"floor":2,"section":"C","shelf":"3"}'::jsonb, current_date from app.products where sku = '6979A542' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MU001794', 'WASHER,RR SUSP SPRING', 'TRITON (2023-PRESENT)', 'Suspension', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 40.32, true, current_date from app.products where sku = 'MU001794' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 50.00, 0, 13, 25, '{"floor":1,"section":"D","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MU001794' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1018A083', 'GEAR,BALANCER SHAFT DRIVE', 'TRITON (2023-PRESENT)', 'Transmission', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 1090.88, true, current_date from app.products where sku = '1018A083' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 6.00, 0, 2, 3, '{"floor":2,"section":"E","shelf":"5"}'::jsonb, current_date from app.products where sku = '1018A083' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1555B094', 'BOLT,CATALYTIC CONVERTER', 'TRITON (2023-PRESENT)', 'Exhaust', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
