-- Product Catalog Seed Part 3 of 4

insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 23.52, true, current_date from app.products where sku = '1555B094' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 20.00, 0, 5, 10, '{"floor":2,"section":"F","shelf":"1"}'::jsonb, current_date from app.products where sku = '1555B094' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1101A044', 'WASHER,CRANKSHAFT PULLEY', 'TRITON (2023-PRESENT)', 'Belts & Pulleys', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 359.52, true, current_date from app.products where sku = '1101A044' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 40.00, 0, 10, 20, '{"floor":1,"section":"G","shelf":"2"}'::jsonb, current_date from app.products where sku = '1101A044' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('11066A000P', 'NUT,GLOW PLUG COV SETTING', 'TRITON (2023-PRESENT)', 'Ignition', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 49.28, true, current_date from app.products where sku = '11066A000P' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 16.00, 0, 4, 8, '{"floor":2,"section":"H","shelf":"3"}'::jsonb, current_date from app.products where sku = '11066A000P' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MU001935', 'CLIP,RELAY', 'TRITON (2023-PRESENT)', 'Electrical', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 26.88, true, current_date from app.products where sku = 'MU001935' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 47.00, 0, 12, 24, '{"floor":2,"section":"A","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MU001935' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF911343', 'BOLT,A/C COMPRESSOR', 'TRITON (2023-PRESENT)', 'Air Conditioning', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 36.96, true, current_date from app.products where sku = 'MF911343' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 50.00, 0, 13, 25, '{"floor":1,"section":"B","shelf":"5"}'::jsonb, current_date from app.products where sku = 'MF911343' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1230A225', 'GASKET,OIL FILTER BRACKET', 'TRITON (2023-PRESENT)', 'Filters', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 131.04, true, current_date from app.products where sku = '1230A225' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 7.00, 0, 2, 4, '{"floor":2,"section":"C","shelf":"1"}'::jsonb, current_date from app.products where sku = '1230A225' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MS240126', 'BOLT,RADIATOR COND TANK', 'TRITON (2023-PRESENT)', 'Cooling', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 56.00, true, current_date from app.products where sku = 'MS240126' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 8.00, 0, 2, 4, '{"floor":2,"section":"D","shelf":"2"}'::jsonb, current_date from app.products where sku = 'MS240126' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8558B422', 'BRACKET,A/T HARNESS', 'TRITON (2023-PRESENT)', 'Steering', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 33.60, true, current_date from app.products where sku = '8558B422' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 6.00, 0, 2, 3, '{"floor":1,"section":"E","shelf":"3"}'::jsonb, current_date from app.products where sku = '8558B422' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MU001368', 'GROMMET,TAIL LAMP', 'TRITON (2023-PRESENT)', 'Lighting', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 71.68, true, current_date from app.products where sku = 'MU001368' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 20.00, 0, 5, 10, '{"floor":2,"section":"F","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MU001368' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF911245', 'BOLT,M/T CLUTCH CONT EQUIP', 'TRITON (2023-PRESENT)', 'Clutch', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 60.48, true, current_date from app.products where sku = 'MF911245' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 43.00, 0, 11, 22, '{"floor":2,"section":"G","shelf":"5"}'::jsonb, current_date from app.products where sku = 'MF911245' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MU001516', 'PLUG,FR DOOR', 'TRITON (2023-PRESENT)', 'Body Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 38.08, true, current_date from app.products where sku = 'MU001516' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 17.00, 0, 5, 9, '{"floor":1,"section":"H","shelf":"1"}'::jsonb, current_date from app.products where sku = 'MU001516' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('4650B995', 'CLIP,BRAKE FLUID LINE', 'TRITON (2023-PRESENT)', 'Brakes', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 36.96, true, current_date from app.products where sku = '4650B995' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 7.00, 0, 2, 4, '{"floor":2,"section":"A","shelf":"2"}'::jsonb, current_date from app.products where sku = '4650B995' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('96309A010P', 'SCREW,RR VIEW MIRROR', 'TRITON (2023-PRESENT)', 'Accessories', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 19.04, true, current_date from app.products where sku = '96309A010P' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 3.00, 0, 1, 2, '{"floor":2,"section":"B","shelf":"3"}'::jsonb, current_date from app.products where sku = '96309A010P' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MS101204', 'BOLT,A/T VALVE BODY INR', 'XFORCE (2024-PRESENT)', 'Engine', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 45.92, true, current_date from app.products where sku = 'MS101204' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 41.00, 0, 11, 21, '{"floor":1,"section":"C","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MS101204' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF911346', 'BOLT,TAILGATE GAS SPRING', 'XFORCE (2024-PRESENT)', 'Suspension', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 56.00, true, current_date from app.products where sku = 'MF911346' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 21.00, 0, 6, 11, '{"floor":2,"section":"D","shelf":"5"}'::jsonb, current_date from app.products where sku = 'MF911346' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF913017', 'BOLT,FLOOR CONSOLE', 'XFORCE (2024-PRESENT)', 'General Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 15.68, true, current_date from app.products where sku = 'MF913017' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 48.00, 0, 12, 24, '{"floor":2,"section":"E","shelf":"1"}'::jsonb, current_date from app.products where sku = 'MF913017' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('80834B010P', 'W/STRIP,FR DOOR BELT,INR R', 'XFORCE (2024-PRESENT)', 'Belts & Pulleys', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 1814.40, true, current_date from app.products where sku = '80834B010P' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 19.00, 0, 5, 10, '{"floor":1,"section":"F","shelf":"2"}'::jsonb, current_date from app.products where sku = '80834B010P' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1230A236', 'GASKET,OIL FILTER BRACKET', 'XFORCE (2024-PRESENT)', 'Filters', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 156.80, true, current_date from app.products where sku = '1230A236' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 18.00, 0, 5, 9, '{"floor":2,"section":"G","shelf":"3"}'::jsonb, current_date from app.products where sku = '1230A236' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MB906064', 'NUT,RADIATOR', 'XFORCE (2024-PRESENT)', 'Cooling', 'Mitsubishi', 'PC', 'out_of_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 70.56, true, current_date from app.products where sku = 'MB906064' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 13.00, 0, 4, 7, '{"floor":2,"section":"H","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MB906064' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MU432003', 'NUT,RR LAMP', 'XFORCE (2024-PRESENT)', 'Lighting', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 79.52, true, current_date from app.products where sku = 'MU432003' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 12.00, 0, 3, 6, '{"floor":1,"section":"A","shelf":"5"}'::jsonb, current_date from app.products where sku = 'MU432003' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MR212302', 'NUT,EXHAUST MANIFOLD', 'XFORCE (2024-PRESENT)', 'Exhaust', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 73.92, true, current_date from app.products where sku = 'MR212302' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 21.00, 0, 6, 11, '{"floor":2,"section":"B","shelf":"1"}'::jsonb, current_date from app.products where sku = 'MR212302' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1801A264', 'NUT,ALTERNATOR', 'XFORCE (2024-PRESENT)', 'Electrical', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 62.72, true, current_date from app.products where sku = '1801A264' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 46.00, 0, 12, 23, '{"floor":2,"section":"C","shelf":"2"}'::jsonb, current_date from app.products where sku = '1801A264' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('5251F078', 'BRACKET,RR WHEELHOUSE,RR', 'XFORCE (2024-PRESENT)', 'Steering', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 41.44, true, current_date from app.products where sku = '5251F078' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 45.00, 0, 12, 23, '{"floor":1,"section":"D","shelf":"3"}'::jsonb, current_date from app.products where sku = '5251F078' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1822A085', 'SPARK PLUG', 'XFORCE (2024-PRESENT)', 'Ignition', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 1221.92, true, current_date from app.products where sku = '1822A085' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 19.00, 0, 5, 10, '{"floor":2,"section":"E","shelf":"4"}'::jsonb, current_date from app.products where sku = '1822A085' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('5713A518', 'SCREW,FR DOOR WINDOW RGLTR', 'XFORCE (2024-PRESENT)', 'Body Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 38.08, true, current_date from app.products where sku = '5713A518' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 41.00, 0, 11, 21, '{"floor":2,"section":"F","shelf":"5"}'::jsonb, current_date from app.products where sku = '5713A518' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF913010', 'BOLT,A/C PIPING', 'XFORCE (2024-PRESENT)', 'Air Conditioning', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 26.88, true, current_date from app.products where sku = 'MF913010' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 26.00, 0, 7, 13, '{"floor":1,"section":"G","shelf":"1"}'::jsonb, current_date from app.products where sku = 'MF913010' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8250A605', 'NUT,WINDSHIELD WIPER', 'XFORCE (2024-PRESENT)', 'Accessories', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 52.64, true, current_date from app.products where sku = '8250A605' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 50.00, 0, 13, 25, '{"floor":2,"section":"H","shelf":"2"}'::jsonb, current_date from app.products where sku = '8250A605' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MB950511', 'PIN,BRAKE M/CYL', 'XFORCE (2024-PRESENT)', 'Brakes', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 71.68, true, current_date from app.products where sku = 'MB950511' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 46.00, 0, 12, 23, '{"floor":2,"section":"A","shelf":"3"}'::jsonb, current_date from app.products where sku = 'MB950511' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('4620A408', 'BRACKET,CLUTCH PEDAL', 'XFORCE (2024-PRESENT)', 'Clutch', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 183.68, true, current_date from app.products where sku = '4620A408' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 26.00, 0, 7, 13, '{"floor":1,"section":"B","shelf":"4"}'::jsonb, current_date from app.products where sku = '4620A408' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('9499D171', 'VALVE,HEV O/CLR BY-PASS', 'OUTLANDER (2015-PRESENT)', 'Engine', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 9060.80, true, current_date from app.products where sku = '9499D171' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 21.00, 0, 6, 11, '{"floor":2,"section":"C","shelf":"5"}'::jsonb, current_date from app.products where sku = '9499D171' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1000C528', 'GASKET KIT,ENG OVERHAUL', 'OUTLANDER (2015-PRESENT)', 'Engine', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 28208.32, true, current_date from app.products where sku = '1000C528' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 20.00, 0, 5, 10, '{"floor":2,"section":"D","shelf":"1"}'::jsonb, current_date from app.products where sku = '1000C528' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1340A130', 'BELT,WATER PUMP', 'OUTLANDER (2015-PRESENT)', 'Belts & Pulleys', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 647.36, true, current_date from app.products where sku = '1340A130' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 9.00, 0, 3, 5, '{"floor":1,"section":"E","shelf":"2"}'::jsonb, current_date from app.products where sku = '1340A130' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1141A013', 'TENSIONER,TIMING CHAIN', 'OUTLANDER (2015-PRESENT)', 'Belts & Pulleys', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 2709.28, true, current_date from app.products where sku = '1141A013' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 11.00, 0, 3, 6, '{"floor":2,"section":"F","shelf":"3"}'::jsonb, current_date from app.products where sku = '1141A013' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1310A079', 'HOSE,COOLING WATER LINE', 'OUTLANDER (2015-PRESENT)', 'General Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 424.48, true, current_date from app.products where sku = '1310A079' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 4.00, 0, 1, 2, '{"floor":2,"section":"G","shelf":"4"}'::jsonb, current_date from app.products where sku = '1310A079' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MZ590921EX', 'FLR ILLUMI', 'OUTLANDER (2015-PRESENT)', 'General Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 13501.60, true, current_date from app.products where sku = 'MZ590921EX' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 1.00, 0, 1, 1, '{"floor":1,"section":"H","shelf":"5"}'::jsonb, current_date from app.products where sku = 'MZ590921EX' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1370A665', 'HOSE,RADIATOR,UPR', 'OUTLANDER (2015-PRESENT)', 'Cooling', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 3004.96, true, current_date from app.products where sku = '1370A665' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 19.00, 0, 5, 10, '{"floor":2,"section":"A","shelf":"1"}'::jsonb, current_date from app.products where sku = '1370A665' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('7450A643', 'GRILLE,RADIATOR', 'OUTLANDER (2015-PRESENT)', 'Cooling', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 21512.96, true, current_date from app.products where sku = '7450A643' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 44.00, 0, 11, 22, '{"floor":2,"section":"B","shelf":"2"}'::jsonb, current_date from app.products where sku = '7450A643' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1571B816', 'MUFFLER,EXHAUST MAIN', 'OUTLANDER (2015-PRESENT)', 'Exhaust', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 15452.64, true, current_date from app.products where sku = '1571B816' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 28.00, 0, 7, 14, '{"floor":1,"section":"C","shelf":"3"}'::jsonb, current_date from app.products where sku = '1571B816' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1570D381', 'PIPE,EXHAUST,CTR', 'OUTLANDER (2015-PRESENT)', 'Exhaust', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 23344.16, true, current_date from app.products where sku = '1570D381' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 11.00, 0, 3, 6, '{"floor":2,"section":"D","shelf":"4"}'::jsonb, current_date from app.products where sku = '1570D381' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1822A068', 'SPARK PLUG', 'OUTLANDER (2015-PRESENT)', 'Ignition', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 1432.48, true, current_date from app.products where sku = '1822A068' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 34.00, 0, 9, 17, '{"floor":2,"section":"E","shelf":"5"}'::jsonb, current_date from app.products where sku = '1822A068' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1832A062', 'COIL,IGNITION', 'OUTLANDER (2015-PRESENT)', 'Ignition', 'Mitsubishi', 'PC', 'out_of_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 7917.28, true, current_date from app.products where sku = '1832A062' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 14.00, 0, 4, 7, '{"floor":1,"section":"F","shelf":"1"}'::jsonb, current_date from app.products where sku = '1832A062' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8651A247XA', 'SENSOR,CORNER CLEARANCE', 'OUTLANDER (2015-PRESENT)', 'Electrical', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 8757.28, true, current_date from app.products where sku = '8651A247XA' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 19.00, 0, 5, 10, '{"floor":2,"section":"G","shelf":"2"}'::jsonb, current_date from app.products where sku = '8651A247XA' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8201A216', 'BATTERY', 'OUTLANDER (2015-PRESENT)', 'Electrical', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 41006.56, true, current_date from app.products where sku = '8201A216' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 22.00, 0, 6, 11, '{"floor":2,"section":"H","shelf":"3"}'::jsonb, current_date from app.products where sku = '8201A216' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MN183955', 'LOCK,VALVE SPRING RETAINER', 'OUTLANDER (2015-PRESENT)', 'Suspension', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 86.24, true, current_date from app.products where sku = 'MN183955' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 30.00, 0, 8, 15, '{"floor":1,"section":"A","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MN183955' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('4060A417', 'INSULATOR,FR SUSP STRUT', 'OUTLANDER (2015-PRESENT)', 'Suspension', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 3769.92, true, current_date from app.products where sku = '4060A417' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 47.00, 0, 12, 24, '{"floor":2,"section":"B","shelf":"5"}'::jsonb, current_date from app.products where sku = '4060A417' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('4422A143', 'TIE ROD,STEERING', 'OUTLANDER (2015-PRESENT)', 'Steering', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 3234.56, true, current_date from app.products where sku = '4422A143' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 25.00, 0, 7, 13, '{"floor":2,"section":"C","shelf":"1"}'::jsonb, current_date from app.products where sku = '4422A143' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('7661A227', 'RACK,ROOF,LH', 'OUTLANDER (2015-PRESENT)', 'Steering', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 24494.40, true, current_date from app.products where sku = '7661A227' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 9.00, 0, 3, 5, '{"floor":1,"section":"D","shelf":"2"}'::jsonb, current_date from app.products where sku = '7661A227' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('4605B910', 'SEAL KIT,RR BRAKE CALIPER', 'OUTLANDER (2015-PRESENT)', 'Brakes', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 1282.40, true, current_date from app.products where sku = '4605B910' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 47.00, 0, 12, 24, '{"floor":2,"section":"E","shelf":"3"}'::jsonb, current_date from app.products where sku = '4605B910' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('4605B806', 'PAD SET,RR BRAKE', 'OUTLANDER (2015-PRESENT)', 'Brakes', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 5070.24, true, current_date from app.products where sku = '4605B806' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 9.00, 0, 3, 5, '{"floor":2,"section":"F","shelf":"4"}'::jsonb, current_date from app.products where sku = '4605B806' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('6405A209', 'COVER,FR BUMPER,LH', 'OUTLANDER (2015-PRESENT)', 'Body Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 259.84, true, current_date from app.products where sku = '6405A209' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 35.00, 0, 9, 18, '{"floor":1,"section":"G","shelf":"5"}'::jsonb, current_date from app.products where sku = '6405A209' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('5706A584', 'GLASS,FR DOOR WINDOW,RH', 'OUTLANDER (2015-PRESENT)', 'Body Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 19824.00, true, current_date from app.products where sku = '5706A584' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 41.00, 0, 11, 21, '{"floor":2,"section":"H","shelf":"1"}'::jsonb, current_date from app.products where sku = '5706A584' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8264A312XA', 'COVER,HEADLAMP WASHER HOLE', 'OUTLANDER (2015-PRESENT)', 'Lighting', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 1498.56, true, current_date from app.products where sku = '8264A312XA' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 4.00, 0, 1, 2, '{"floor":2,"section":"A","shelf":"2"}'::jsonb, current_date from app.products where sku = '8264A312XA' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8321A748', 'LAMP ASSY,FOG,FR RH', 'OUTLANDER (2015-PRESENT)', 'Lighting', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 10339.84, true, current_date from app.products where sku = '8321A748' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 32.00, 0, 8, 16, '{"floor":1,"section":"B","shelf":"3"}'::jsonb, current_date from app.products where sku = '8321A748' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8250B038', 'BLADE,WINDSHIELD WIPER,RH', 'OUTLANDER (2015-PRESENT)', 'Accessories', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 462.56, true, current_date from app.products where sku = '8250B038' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 20.00, 0, 5, 10, '{"floor":2,"section":"C","shelf":"4"}'::jsonb, current_date from app.products where sku = '8250B038' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('6107A052', 'MOULDING,WINDSHILD SIDE', 'OUTLANDER (2015-PRESENT)', 'Accessories', 'Mitsubishi', 'PC', 'out_of_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 2914.24, true, current_date from app.products where sku = '6107A052' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 49.00, 0, 13, 25, '{"floor":2,"section":"D","shelf":"5"}'::jsonb, current_date from app.products where sku = '6107A052' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('3200A102', 'GASKET,T/F OIL DRAIN PLUG', 'LANCER CY4 (2007-2014)', 'Engine', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 110.88, true, current_date from app.products where sku = '3200A102' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 40.00, 0, 10, 20, '{"floor":1,"section":"E","shelf":"1"}'::jsonb, current_date from app.products where sku = '3200A102' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('CP7030A950', 'INFLATOR KIT, AIR BAG', 'LANCER CY4 (2007-2014)', 'General Parts', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 0.01, true, current_date from app.products where sku = 'CP7030A950' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 22.00, 0, 6, 11, '{"floor":2,"section":"F","shelf":"2"}'::jsonb, current_date from app.products where sku = 'CP7030A950' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF140275', 'BOLT,EXHAUST PIPE', 'LANCER CY4 (2007-2014)', 'Exhaust', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 327.04, true, current_date from app.products where sku = 'MF140275' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 29.00, 0, 8, 15, '{"floor":2,"section":"G","shelf":"3"}'::jsonb, current_date from app.products where sku = 'MF140275' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('4429A001', 'SCREW,STEERING WHEEL', 'LANCER CY4 (2007-2014)', 'Steering', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 143.36, true, current_date from app.products where sku = '4429A001' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 28.00, 0, 7, 14, '{"floor":1,"section":"H","shelf":"4"}'::jsonb, current_date from app.products where sku = '4429A001' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('11950W010P', 'BELT,P/S', 'LANCER CY4 (2007-2014)', 'Belts & Pulleys', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 1171.52, true, current_date from app.products where sku = '11950W010P' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 22.00, 0, 6, 11, '{"floor":2,"section":"A","shelf":"5"}'::jsonb, current_date from app.products where sku = '11950W010P' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MN187246', 'GASKET,WATER PUMP', 'LANCER CY4 (2007-2014)', 'Cooling', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 268.80, true, current_date from app.products where sku = 'MN187246' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 20.00, 0, 5, 10, '{"floor":2,"section":"B","shelf":"1"}'::jsonb, current_date from app.products where sku = 'MN187246' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('7815A656', 'CLIP,A/C PIPING', 'LANCER CY4 (2007-2014)', 'Air Conditioning', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 116.48, true, current_date from app.products where sku = '7815A656' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 16.00, 0, 4, 8, '{"floor":1,"section":"C","shelf":"2"}'::jsonb, current_date from app.products where sku = '7815A656' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1801A079', 'BOLT,ALTERNATOR', 'LANCER CY4 (2007-2014)', 'Electrical', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 169.12, true, current_date from app.products where sku = '1801A079' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 46.00, 0, 12, 23, '{"floor":2,"section":"D","shelf":"3"}'::jsonb, current_date from app.products where sku = '1801A079' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());
