-- Product Catalog Seed Part 1 of 4

-- Generated from web-app/src/data/productData.js
-- Usage: node supabase/scripts/export-product-seed.mjs > supabase/generated/product_catalog_seed.sql

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MS200124', 'SCREW,LOCK CYLINDER', 'XPANDER (2017-PRESENT)', 'Engine', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 19.04, true, current_date from app.products where sku = 'MS200124' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 9.00, 0, 3, 5, '{"floor":2,"section":"B","shelf":"2"}'::jsonb, current_date from app.products where sku = 'MS200124' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('CPMW400258', 'PUMP KIT,FUEL', 'XPANDER (2017-PRESENT)', 'General Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 0.01, true, current_date from app.products where sku = 'CPMW400258' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 8.00, 0, 2, 4, '{"floor":2,"section":"C","shelf":"3"}'::jsonb, current_date from app.products where sku = 'CPMW400258' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2782A103', 'SPRING,A/T PARKING LEVER', 'XPANDER (2017-PRESENT)', 'Suspension', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 86.24, true, current_date from app.products where sku = '2782A103' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 50.00, 0, 13, 25, '{"floor":1,"section":"D","shelf":"4"}'::jsonb, current_date from app.products where sku = '2782A103' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1555B003', 'COLLAR,EXHAUST MANIFOLD', 'XPANDER (2017-PRESENT)', 'Exhaust', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 336.00, true, current_date from app.products where sku = '1555B003' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 20.00, 0, 5, 10, '{"floor":2,"section":"E","shelf":"5"}'::jsonb, current_date from app.products where sku = '1555B003' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1101A015', 'WASHER,CRANKSHAFT PULLEY', 'XPANDER (2017-PRESENT)', 'Belts & Pulleys', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 327.04, true, current_date from app.products where sku = '1101A015' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 2.00, 0, 1, 1, '{"floor":2,"section":"F","shelf":"1"}'::jsonb, current_date from app.products where sku = '1101A015' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2921A006', 'O-RING,A/T CASE OIL FILTER', 'XPANDER (2017-PRESENT)', 'Filters', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 148.96, true, current_date from app.products where sku = '2921A006' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 25.00, 0, 7, 13, '{"floor":1,"section":"G","shelf":"2"}'::jsonb, current_date from app.products where sku = '2921A006' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1355A520', 'BOLT,RADIATOR', 'XPANDER (2017-PRESENT)', 'Cooling', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 63.84, true, current_date from app.products where sku = '1355A520' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 38.00, 0, 10, 19, '{"floor":2,"section":"H","shelf":"3"}'::jsonb, current_date from app.products where sku = '1355A520' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MS810969', 'FUSE,CHASSIS WIRING (30A)', 'XPANDER (2017-PRESENT)', 'Electrical', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 73.92, true, current_date from app.products where sku = 'MS810969' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 31.00, 0, 8, 16, '{"floor":2,"section":"A","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MS810969' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MS240268', 'BOLT,RR DOOR LOCKING', 'XPANDER (2017-PRESENT)', 'Body Parts', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 48.16, true, current_date from app.products where sku = 'MS240268' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 19.00, 0, 5, 10, '{"floor":1,"section":"B","shelf":"5"}'::jsonb, current_date from app.products where sku = 'MS240268' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('7842A229', 'SCREW,RR A/C', 'XPANDER (2017-PRESENT)', 'Air Conditioning', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 38.08, true, current_date from app.products where sku = '7842A229' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 37.00, 0, 10, 19, '{"floor":2,"section":"C","shelf":"1"}'::jsonb, current_date from app.products where sku = '7842A229' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MB409439', 'SCREW,STEERING COLUMN COVE', 'XPANDER (2017-PRESENT)', 'Steering', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 67.20, true, current_date from app.products where sku = 'MB409439' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 29.00, 0, 8, 15, '{"floor":2,"section":"D","shelf":"2"}'::jsonb, current_date from app.products where sku = 'MB409439' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1822A086', 'SPARK PLUG', 'XPANDER (2017-PRESENT)', 'Ignition', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 1167.04, true, current_date from app.products where sku = '1822A086' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 33.00, 0, 9, 17, '{"floor":1,"section":"E","shelf":"3"}'::jsonb, current_date from app.products where sku = '1822A086' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2348A357', 'CLIP,M/T CLUTCH CONT EQUIP', 'XPANDER (2017-PRESENT)', 'Clutch', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 82.88, true, current_date from app.products where sku = '2348A357' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 13.00, 0, 4, 7, '{"floor":2,"section":"F","shelf":"4"}'::jsonb, current_date from app.products where sku = '2348A357' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MN106321', 'SCREW,DOOR LAMP SWITCH', 'XPANDER (2017-PRESENT)', 'Lighting', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 60.48, true, current_date from app.products where sku = 'MN106321' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 33.00, 0, 9, 17, '{"floor":2,"section":"G","shelf":"5"}'::jsonb, current_date from app.products where sku = 'MN106321' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2782A101', 'SHAFT,A/T PARKING PAWL', 'XPANDER (2017-PRESENT)', 'Transmission', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 299.04, true, current_date from app.products where sku = '2782A101' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 10.00, 0, 3, 5, '{"floor":1,"section":"H","shelf":"1"}'::jsonb, current_date from app.products where sku = '2782A101' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MR478263', 'GROMMET,DRIP MOULDING', 'XPANDER (2017-PRESENT)', 'Accessories', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 95.20, true, current_date from app.products where sku = 'MR478263' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 43.00, 0, 11, 22, '{"floor":2,"section":"A","shelf":"2"}'::jsonb, current_date from app.products where sku = 'MR478263' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF913160', 'BOLT,BRAKE BOOSTER', 'XPANDER (2017-PRESENT)', 'Brakes', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 60.48, true, current_date from app.products where sku = 'MF913160' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 8.00, 0, 2, 4, '{"floor":2,"section":"B","shelf":"3"}'::jsonb, current_date from app.products where sku = 'MF913160' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('26120W010P', 'LAMP ASSY,FOG,FR', 'MONTERO (2015-PRESENT)', 'Lighting', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 5723.20, true, current_date from app.products where sku = '26120W010P' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 38.00, 0, 10, 19, '{"floor":1,"section":"C","shelf":"4"}'::jsonb, current_date from app.products where sku = '26120W010P' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF140208', 'BOLT,CYLINDER BLOCK', 'MONTERO CR45 (2008-2015)', 'Engine', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 57.12, true, current_date from app.products where sku = 'MF140208' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 5.00, 0, 2, 3, '{"floor":2,"section":"D","shelf":"5"}'::jsonb, current_date from app.products where sku = 'MF140208' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('6958A087', 'BOLT,3RD SEAT', 'MONTERO CR45 (2008-2015)', 'General Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 14.56, true, current_date from app.products where sku = '6958A087' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 43.00, 0, 11, 22, '{"floor":2,"section":"E","shelf":"1"}'::jsonb, current_date from app.products where sku = '6958A087' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('CP5802A709', 'SPRING,SET GAS', 'MONTERO CR45 (2008-2015)', 'Suspension', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 0.01, true, current_date from app.products where sku = 'CP5802A709' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 3.00, 0, 1, 2, '{"floor":1,"section":"F","shelf":"2"}'::jsonb, current_date from app.products where sku = 'CP5802A709' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1570A178', 'BRACKET,EXHAUST FR PIPE', 'MONTERO CR45 (2008-2015)', 'Exhaust', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 257.60, true, current_date from app.products where sku = '1570A178' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 7.00, 0, 2, 4, '{"floor":2,"section":"G","shelf":"3"}'::jsonb, current_date from app.products where sku = '1570A178' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8701A062', 'BRACKET,AUDIO EQUIP', 'MONTERO CR45 (2008-2015)', 'Steering', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 151.20, true, current_date from app.products where sku = '8701A062' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 7.00, 0, 2, 4, '{"floor":2,"section":"H","shelf":"4"}'::jsonb, current_date from app.products where sku = '8701A062' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MN119812', 'WASHER,CRANKSHAFT PULLEY', 'MONTERO CR45 (2008-2015)', 'Belts & Pulleys', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 264.32, true, current_date from app.products where sku = 'MN119812' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 40.00, 0, 10, 20, '{"floor":1,"section":"A","shelf":"5"}'::jsonb, current_date from app.products where sku = 'MN119812' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8503A088', 'HARNESS,FUEL FILTER SENSOR', 'MONTERO CR45 (2008-2015)', 'Filters', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 256.48, true, current_date from app.products where sku = '8503A088' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 49.00, 0, 13, 25, '{"floor":2,"section":"B","shelf":"1"}'::jsonb, current_date from app.products where sku = '8503A088' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1370A249', 'CLIP,RADIATOR PIPING', 'MONTERO CR45 (2008-2015)', 'Cooling', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 115.36, true, current_date from app.products where sku = '1370A249' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 19.00, 0, 5, 10, '{"floor":2,"section":"C","shelf":"2"}'::jsonb, current_date from app.products where sku = '1370A249' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2340A104', 'BUSHING,CLUTCH PEDAL', 'MONTERO CR45 (2008-2015)', 'Clutch', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 204.96, true, current_date from app.products where sku = '2340A104' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 37.00, 0, 10, 19, '{"floor":1,"section":"D","shelf":"3"}'::jsonb, current_date from app.products where sku = '2340A104' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('5729A004', 'PLUG,FR DOOR', 'MONTERO CR45 (2008-2015)', 'Body Parts', 'Mitsubishi', 'PC', 'out_of_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 53.76, true, current_date from app.products where sku = '5729A004' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 22.00, 0, 6, 11, '{"floor":2,"section":"E","shelf":"4"}'::jsonb, current_date from app.products where sku = '5729A004' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MR360998', 'O-RING,A/C PIPING', 'MONTERO CR45 (2008-2015)', 'Air Conditioning', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 49.28, true, current_date from app.products where sku = 'MR360998' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 40.00, 0, 10, 20, '{"floor":2,"section":"F","shelf":"5"}'::jsonb, current_date from app.products where sku = 'MR360998' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8475A004', 'BULB,INST PANEL SWITCH', 'MONTERO CR45 (2008-2015)', 'Lighting', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 99.68, true, current_date from app.products where sku = '8475A004' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 20.00, 0, 5, 10, '{"floor":1,"section":"G","shelf":"1"}'::jsonb, current_date from app.products where sku = '8475A004' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('7430A161', 'LABEL,FUSE', 'MONTERO CR45 (2008-2015)', 'Electrical', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 101.92, true, current_date from app.products where sku = '7430A161' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 46.00, 0, 12, 23, '{"floor":2,"section":"H","shelf":"2"}'::jsonb, current_date from app.products where sku = '7430A161' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1863A001', 'BRACKET,GLOW PLUG RELAY', 'MONTERO CR45 (2008-2015)', 'Ignition', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 399.84, true, current_date from app.products where sku = '1863A001' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 10.00, 0, 3, 5, '{"floor":2,"section":"A","shelf":"3"}'::jsonb, current_date from app.products where sku = '1863A001' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MR111091', 'GEAR,SPEEDOMETER DRIVEN', 'MONTERO CR45 (2008-2015)', 'Transmission', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 1908.48, true, current_date from app.products where sku = 'MR111091' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 50.00, 0, 13, 25, '{"floor":1,"section":"B","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MR111091' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('4600A104', 'SNAP RING,RR BRAKE', 'MONTERO CR45 (2008-2015)', 'Brakes', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 49.28, true, current_date from app.products where sku = '4600A104' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 1.00, 0, 1, 1, '{"floor":2,"section":"C","shelf":"5"}'::jsonb, current_date from app.products where sku = '4600A104' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8050A186', 'GARNISH,I/PNL,CTR', 'MONTERO CR45 (2008-2015)', 'Accessories', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 85.12, true, current_date from app.products where sku = '8050A186' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 11.00, 0, 3, 6, '{"floor":2,"section":"D","shelf":"1"}'::jsonb, current_date from app.products where sku = '8050A186' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('ME193855', 'OIL JET,TIMING GEAR CASE', 'MONTERO CR45 (2008-2015)', 'Fluids & Oils', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 4887.68, true, current_date from app.products where sku = 'ME193855' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 18.00, 0, 5, 9, '{"floor":1,"section":"E","shelf":"2"}'::jsonb, current_date from app.products where sku = 'ME193855' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF241226', 'BOLT,CYLINDER HEAD', 'STRADA SU (2015-PRESENT)', 'Engine', 'Mitsubishi', 'PC', 'out_of_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 64.96, true, current_date from app.products where sku = 'MF241226' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 7.00, 0, 2, 4, '{"floor":2,"section":"F","shelf":"3"}'::jsonb, current_date from app.products where sku = 'MF241226' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('BL000002', 'NUTS AND BOLTS', 'STRADA SU (2015-PRESENT)', 'General Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 0.01, true, current_date from app.products where sku = 'BL000002' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 6.00, 0, 2, 3, '{"floor":2,"section":"G","shelf":"4"}'::jsonb, current_date from app.products where sku = 'BL000002' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1340A194', 'BELT,ALTERNATOR & OTHERS', 'STRADA SU (2015-PRESENT)', 'Belts & Pulleys', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 498.40, true, current_date from app.products where sku = '1340A194' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 17.00, 0, 5, 9, '{"floor":1,"section":"H","shelf":"5"}'::jsonb, current_date from app.products where sku = '1340A194' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF243660', 'BOLT,RADIATOR', 'STRADA SU (2015-PRESENT)', 'Cooling', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 99.68, true, current_date from app.products where sku = 'MF243660' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 47.00, 0, 12, 24, '{"floor":2,"section":"A","shelf":"1"}'::jsonb, current_date from app.products where sku = 'MF243660' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('6400J260', 'CLIP,RR BUMPER', 'STRADA SU (2015-PRESENT)', 'Body Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 51.52, true, current_date from app.products where sku = '6400J260' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 41.00, 0, 11, 21, '{"floor":2,"section":"B","shelf":"2"}'::jsonb, current_date from app.products where sku = '6400J260' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1570B869', 'PIPE,EXHAUST,FR', 'STRADA SU (2015-PRESENT)', 'Exhaust', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 4024.16, true, current_date from app.products where sku = '1570B869' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 44.00, 0, 11, 22, '{"floor":1,"section":"C","shelf":"3"}'::jsonb, current_date from app.products where sku = '1570B869' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MR568456', 'O-RING,A/C PIPING', 'STRADA SU (2015-PRESENT)', 'Air Conditioning', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 88.48, true, current_date from app.products where sku = 'MR568456' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 38.00, 0, 10, 19, '{"floor":2,"section":"D","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MR568456' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('7821A137', 'BULB,HEATER CONTROL PANEL', 'STRADA SU (2015-PRESENT)', 'Lighting', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 86.24, true, current_date from app.products where sku = '7821A137' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 22.00, 0, 6, 11, '{"floor":2,"section":"E","shelf":"5"}'::jsonb, current_date from app.products where sku = '7821A137' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MZ691066', 'CABIN AIR FILTER', 'STRADA SU (2015-PRESENT)', 'Filters', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 566.72, true, current_date from app.products where sku = 'MZ691066' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 16.00, 0, 4, 8, '{"floor":1,"section":"F","shelf":"1"}'::jsonb, current_date from app.products where sku = 'MZ691066' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF911698', 'BOLT,STARTER', 'STRADA SU (2015-PRESENT)', 'Electrical', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 161.28, true, current_date from app.products where sku = 'MF911698' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 48.00, 0, 12, 24, '{"floor":2,"section":"G","shelf":"2"}'::jsonb, current_date from app.products where sku = 'MF911698' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('7812A131', 'BRACKET,A/C CONDENSER', 'STRADA SU (2015-PRESENT)', 'Steering', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 172.48, true, current_date from app.products where sku = '7812A131' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 48.00, 0, 12, 24, '{"floor":2,"section":"H","shelf":"3"}'::jsonb, current_date from app.products where sku = '7812A131' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8541F771', 'HARN,GLOW PLUG CONT RELAY', 'STRADA SU (2015-PRESENT)', 'Ignition', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 940.80, true, current_date from app.products where sku = '8541F771' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 7.00, 0, 2, 4, '{"floor":1,"section":"A","shelf":"4"}'::jsonb, current_date from app.products where sku = '8541F771' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2345A075', 'RESERVOIR,CLUTCH FLUID', 'STRADA SU (2015-PRESENT)', 'Clutch', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 146.72, true, current_date from app.products where sku = '2345A075' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 3.00, 0, 1, 2, '{"floor":2,"section":"B","shelf":"5"}'::jsonb, current_date from app.products where sku = '2345A075' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2782A022', 'SHAFT,A/T PARKING PAWL', 'STRADA SU (2015-PRESENT)', 'Transmission', 'Mitsubishi', 'PC', 'out_of_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 528.64, true, current_date from app.products where sku = '2782A022' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 5.00, 0, 2, 3, '{"floor":2,"section":"C","shelf":"1"}'::jsonb, current_date from app.products where sku = '2782A022' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('4152A020', 'BUSHING,RR SUSP SPRING', 'STRADA SU (2015-PRESENT)', 'Suspension', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 79.52, true, current_date from app.products where sku = '4152A020' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 3.00, 0, 1, 2, '{"floor":1,"section":"D","shelf":"2"}'::jsonb, current_date from app.products where sku = '4152A020' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('4600A495', 'PIN,RR BRAKE', 'STRADA SU (2015-PRESENT)', 'Brakes', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 85.12, true, current_date from app.products where sku = '4600A495' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 31.00, 0, 8, 16, '{"floor":2,"section":"E","shelf":"3"}'::jsonb, current_date from app.products where sku = '4600A495' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('BL000001', 'MOULDING', 'STRADA SU (2015-PRESENT)', 'Accessories', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 0.01, true, current_date from app.products where sku = 'BL000001' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 1.00, 0, 1, 1, '{"floor":2,"section":"F","shelf":"4"}'::jsonb, current_date from app.products where sku = 'BL000001' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF660036', 'GASKET,ROCKER COVER (10)', 'STRADA CR (2005-2013)', 'Engine', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 84.00, true, current_date from app.products where sku = 'MF660036' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 4.00, 0, 1, 2, '{"floor":1,"section":"G","shelf":"5"}'::jsonb, current_date from app.products where sku = 'MF660036' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('CP7030A879', 'INFLATOR KIT, AIR BAG', 'STRADA CR (2005-2013)', 'General Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 0.01, true, current_date from app.products where sku = 'CP7030A879' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 1.00, 0, 1, 1, '{"floor":2,"section":"H","shelf":"1"}'::jsonb, current_date from app.products where sku = 'CP7030A879' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1225A052', 'TUBE,EXHAUST CAMSHAFT OIL', 'STRADA CR (2005-2013)', 'Exhaust', 'Mitsubishi', 'PC', 'out_of_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 290.08, true, current_date from app.products where sku = '1225A052' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 40.00, 0, 10, 20, '{"floor":2,"section":"A","shelf":"2"}'::jsonb, current_date from app.products where sku = '1225A052' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MB958692', 'BELT,A/C (VSP-MZ690290)', 'STRADA CR (2005-2013)', 'Belts & Pulleys', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 646.24, true, current_date from app.products where sku = 'MB958692' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 29.00, 0, 8, 15, '{"floor":1,"section":"B","shelf":"3"}'::jsonb, current_date from app.products where sku = 'MB958692' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8002A290', 'BRACKET,INSTRUMENT PANEL', 'STRADA CR (2005-2013)', 'Steering', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 128.80, true, current_date from app.products where sku = '8002A290' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 45.00, 0, 12, 23, '{"floor":2,"section":"C","shelf":"4"}'::jsonb, current_date from app.products where sku = '8002A290' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1770A050', 'PROTECTOR,FUEL FILTER', 'STRADA CR (2005-2013)', 'Filters', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 1219.68, true, current_date from app.products where sku = '1770A050' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 19.00, 0, 5, 10, '{"floor":2,"section":"D","shelf":"5"}'::jsonb, current_date from app.products where sku = '1770A050' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MN171605', 'SEAL,RADIATOR CONDENSER TANK', 'STRADA CR (2005-2013)', 'Cooling', 'Mitsubishi', 'PC', 'low_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 104.16, true, current_date from app.products where sku = 'MN171605' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 18.00, 0, 5, 9, '{"floor":1,"section":"E","shelf":"1"}'::jsonb, current_date from app.products where sku = 'MN171605' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8558A893', 'BRACKET,BATTERY', 'STRADA CR (2005-2013)', 'Electrical', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 178.08, true, current_date from app.products where sku = '8558A893' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 7.00, 0, 2, 4, '{"floor":2,"section":"F","shelf":"2"}'::jsonb, current_date from app.products where sku = '8558A893' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1820A009', 'GLOW PLUG', 'STRADA CR (2005-2013)', 'Ignition', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 2110.08, true, current_date from app.products where sku = '1820A009' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 26.00, 0, 7, 13, '{"floor":2,"section":"G","shelf":"3"}'::jsonb, current_date from app.products where sku = '1820A009' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());
