-- Product Catalog Seed Part 4 of 4


insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MN163236', 'SPARK PLUG(FR6EI)', 'LANCER CY4 (2007-2014)', 'Ignition', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 1093.12, true, current_date from app.products where sku = 'MN163236' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 30.00, 0, 8, 15, '{"floor":2,"section":"E","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MN163236' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2348A285', 'TUBE,CLUTCH M/CYL', 'LANCER CY4 (2007-2014)', 'Clutch', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 1018.08, true, current_date from app.products where sku = '2348A285' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 34.00, 0, 9, 17, '{"floor":1,"section":"F","shelf":"5"}'::jsonb, current_date from app.products where sku = '2348A285' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MU440019', 'NUT,FR BUMPER', 'LANCER CY4 (2007-2014)', 'Body Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 85.12, true, current_date from app.products where sku = 'MU440019' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 22.00, 0, 6, 11, '{"floor":2,"section":"G","shelf":"1"}'::jsonb, current_date from app.products where sku = 'MU440019' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2528A234', 'GEAR,M/T INPUT SHAFT 5TH', 'LANCER CY4 (2007-2014)', 'Transmission', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 5974.08, true, current_date from app.products where sku = '2528A234' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 5.00, 0, 2, 3, '{"floor":2,"section":"H","shelf":"2"}'::jsonb, current_date from app.products where sku = '2528A234' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MB109960', 'COVER,FR SUSP STRUT', 'LANCER CY4 (2007-2014)', 'Suspension', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 172.48, true, current_date from app.products where sku = 'MB109960' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 12.00, 0, 3, 6, '{"floor":1,"section":"A","shelf":"3"}'::jsonb, current_date from app.products where sku = 'MB109960' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('CP4630A001', 'SEAL,BRAKE BOOSTER BODY', 'LANCER CY4 (2007-2014)', 'Brakes', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 0.01, true, current_date from app.products where sku = 'CP4630A001' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 11.00, 0, 3, 6, '{"floor":2,"section":"B","shelf":"4"}'::jsonb, current_date from app.products where sku = 'CP4630A001' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MU000367', 'GROMMET,TAIL LAMP', 'LANCER CY4 (2007-2014)', 'Lighting', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 108.64, true, current_date from app.products where sku = 'MU000367' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 36.00, 0, 9, 18, '{"floor":2,"section":"C","shelf":"5"}'::jsonb, current_date from app.products where sku = 'MU000367' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('7403A143', 'CLIP,DRIP MOULDING', 'LANCER CY4 (2007-2014)', 'Accessories', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 152.32, true, current_date from app.products where sku = '7403A143' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 18.00, 0, 5, 9, '{"floor":1,"section":"D","shelf":"1"}'::jsonb, current_date from app.products where sku = '7403A143' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MD758684', 'OIL FILTER,A/T VALVE BOD', 'LANCER CY4 (2007-2014)', 'Filters', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 3925.60, true, current_date from app.products where sku = 'MD758684' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 50.00, 0, 13, 25, '{"floor":2,"section":"E","shelf":"2"}'::jsonb, current_date from app.products where sku = 'MD758684' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1226A029', 'GASKET,T/C OIL RETURN TUBE', 'MONTERO QX (2015-PRESENT)', 'Engine', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 5.60, true, current_date from app.products where sku = '1226A029' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 30.00, 0, 8, 15, '{"floor":2,"section":"F","shelf":"3"}'::jsonb, current_date from app.products where sku = '1226A029' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF453107', 'SCREW,FUEL FILLER LID LOCK', 'MONTERO QX (2015-PRESENT)', 'General Parts', 'Mitsubishi', 'PC', 'out_of_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 32.48, true, current_date from app.products where sku = 'MF453107' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 13.00, 0, 4, 7, '{"floor":1,"section":"G","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MF453107' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('CP5802A706', 'SPRING,SET GAS', 'MONTERO QX (2015-PRESENT)', 'Suspension', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 0.01, true, current_date from app.products where sku = 'CP5802A706' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 43.00, 0, 11, 22, '{"floor":2,"section":"H","shelf":"5"}'::jsonb, current_date from app.products where sku = 'CP5802A706' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1515A190', 'BOLT,CATALYTIC CONVERTER', 'MONTERO QX (2015-PRESENT)', 'Exhaust', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 35.84, true, current_date from app.products where sku = '1515A190' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 44.00, 0, 11, 22, '{"floor":2,"section":"A","shelf":"1"}'::jsonb, current_date from app.products where sku = '1515A190' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('7814A037', 'BELT, A/C', 'MONTERO QX (2015-PRESENT)', 'Belts & Pulleys', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 577.92, true, current_date from app.products where sku = '7814A037' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 31.00, 0, 8, 16, '{"floor":1,"section":"B","shelf":"2"}'::jsonb, current_date from app.products where sku = '7814A037' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1130A230', 'GEAR,INJECTION PUMP DRIVE', 'MONTERO QX (2015-PRESENT)', 'Transmission', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 2992.64, true, current_date from app.products where sku = '1130A230' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 39.00, 0, 10, 20, '{"floor":2,"section":"C","shelf":"3"}'::jsonb, current_date from app.products where sku = '1130A230' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1230A112', 'GASKET,OIL FILTER BRACKET', 'MONTERO QX (2015-PRESENT)', 'Filters', 'Mitsubishi', 'PC', 'out_of_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 310.24, true, current_date from app.products where sku = '1230A112' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 30.00, 0, 8, 15, '{"floor":2,"section":"D","shelf":"4"}'::jsonb, current_date from app.products where sku = '1230A112' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8558B397', 'BRACKET,THROTTLE BOD', 'MONTERO QX (2015-PRESENT)', 'Steering', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 26.88, true, current_date from app.products where sku = '8558B397' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 5.00, 0, 2, 3, '{"floor":1,"section":"E","shelf":"5"}'::jsonb, current_date from app.products where sku = '8558B397' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('1375A434', 'SEAL,RADIATOR COND TANK', 'MONTERO QX (2015-PRESENT)', 'Cooling', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 49.28, true, current_date from app.products where sku = '1375A434' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 7.00, 0, 2, 4, '{"floor":2,"section":"F","shelf":"1"}'::jsonb, current_date from app.products where sku = '1375A434' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MR527683', 'STOPPER,CLUTCH PEDAL', 'MONTERO QX (2015-PRESENT)', 'Clutch', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 126.56, true, current_date from app.products where sku = 'MR527683' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 42.00, 0, 11, 21, '{"floor":2,"section":"G","shelf":"2"}'::jsonb, current_date from app.products where sku = 'MR527683' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MR568455', 'O-RING,A/C PIPING', 'MONTERO QX (2015-PRESENT)', 'Air Conditioning', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 72.80, true, current_date from app.products where sku = 'MR568455' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 15.00, 0, 4, 8, '{"floor":1,"section":"H","shelf":"3"}'::jsonb, current_date from app.products where sku = 'MR568455' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF911146', 'BOLT, HOOD LOCKING', 'MONTERO QX (2015-PRESENT)', 'Body Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 48.16, true, current_date from app.products where sku = 'MF911146' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 39.00, 0, 10, 20, '{"floor":2,"section":"A","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MF911146' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('2400A499', 'BULB,GEARSHIFT LINK', 'MONTERO QX (2015-PRESENT)', 'Lighting', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 92.96, true, current_date from app.products where sku = '2400A499' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 20.00, 0, 5, 10, '{"floor":2,"section":"B","shelf":"5"}'::jsonb, current_date from app.products where sku = '2400A499' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('DP010712', 'MOTOLITE SERVICE BATTERY [3SM]', 'MONTERO QX (2015-PRESENT)', 'Electrical', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 0.01, true, current_date from app.products where sku = 'DP010712' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 29.00, 0, 8, 15, '{"floor":1,"section":"C","shelf":"1"}'::jsonb, current_date from app.products where sku = 'DP010712' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('8541F117', 'HARN,GLOW PLUG CONT RELAY', 'MONTERO QX (2015-PRESENT)', 'Ignition', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 1402.24, true, current_date from app.products where sku = '8541F117' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 48.00, 0, 12, 24, '{"floor":2,"section":"D","shelf":"2"}'::jsonb, current_date from app.products where sku = '8541F117' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('4800A067', 'WASHER,RR BRAKE', 'MONTERO QX (2015-PRESENT)', 'Brakes', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 92.96, true, current_date from app.products where sku = '4800A067' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 10.00, 0, 3, 5, '{"floor":2,"section":"E","shelf":"3"}'::jsonb, current_date from app.products where sku = '4800A067' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('MF205566', 'SCREW,ROOM MIRROR', 'MONTERO QX (2015-PRESENT)', 'Accessories', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 56.00, true, current_date from app.products where sku = 'MF205566' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 20.00, 0, 5, 10, '{"floor":1,"section":"F","shelf":"4"}'::jsonb, current_date from app.products where sku = 'MF205566' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('5070A574', 'BRKT ASSY, NO.1 BODY MTG LH', 'L300', 'General Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 851.20, true, current_date from app.products where sku = '5070A574' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 29.00, 0, 8, 15, '{"floor":2,"section":"G","shelf":"5"}'::jsonb, current_date from app.products where sku = '5070A574' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());

insert into app.products (sku, name, model_name, category, brand, uom, status, metadata) values ('5070A575', 'BRKT ASSY, NO.1 BODY MTG RH', 'L300', 'General Parts', 'Mitsubishi', 'PC', 'in_stock', '{"source":"productData.js"}'::jsonb) on conflict (sku) do update set name = excluded.name, model_name = excluded.model_name, category = excluded.category, status = excluded.status, updated_at = timezone('utc', now());
insert into app.product_prices (product_id, price_type, amount, is_current, effective_from) select id, 'retail', 851.20, true, current_date from app.products where sku = '5070A575' and not exists (select 1 from app.product_prices pp where pp.product_id = app.products.id and pp.price_type = 'retail' and pp.is_current);
insert into app.inventory_balances (product_id, on_hand, reserved, reorder_point, reorder_quantity, location, as_of_date) select id, 12.00, 0, 3, 6, '{"floor":2,"section":"H","shelf":"1"}'::jsonb, current_date from app.products where sku = '5070A575' on conflict (product_id) do update set on_hand = excluded.on_hand, reorder_point = excluded.reorder_point, reorder_quantity = excluded.reorder_quantity, location = excluded.location, updated_at = timezone('utc', now());
